"""
FUTURE_ML_01 - Flask Presentation Dashboard
Presentation layer only. Does NOT retrain the model.
Loads existing outputs generated by the notebook.
All metrics and predictions come directly from notebook outputs / submission.csv.
"""
from pathlib import Path
import pandas as pd
from flask import Flask, render_template, send_from_directory, abort

# --- Robust path handling: resolve relative to project root ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DASHBOARD_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = DASHBOARD_DIR / "templates"
STATIC_DIR = DASHBOARD_DIR / "static"
FIGURES_DIR = PROJECT_ROOT / "reports" / "figures"
SUBMISSION_CANDIDATES = [
    PROJECT_ROOT / "submission.csv",
    PROJECT_ROOT / "notebooks" / "submission.csv",
]
TEST_PATH = PROJECT_ROOT / "data" / "raw" / "test.csv"
TRAIN_PATH = PROJECT_ROOT / "data" / "raw" / "train.csv"

# Verified metrics from notebook (single source of truth) — do not change
RIDGE_WAPE = 0.1854
BASELINE_WAPE = 0.2177
IMPROVEMENT_PCT = 14.7
NAIVE_WAPE = 0.2330

app = Flask(__name__, template_folder=str(TEMPLATES_DIR), static_folder=str(STATIC_DIR))


def load_forecast():
    """Load forecast from submission.csv (root or notebooks fallback). Enrich with test.csv if available."""
    submission_path = None
    for cand in SUBMISSION_CANDIDATES:
        if cand.exists():
            submission_path = cand
            break
    if submission_path is None:
        return {
            "found": False,
            "submission_path": None,
            "df": None,
            "enriched": None,
            "summary": None,
            "error": f"No submission file found. Checked: {', '.join(str(p) for p in SUBMISSION_CANDIDATES)}",
        }
    try:
        df = pd.read_csv(submission_path)
        if "id" not in df.columns or "sales" not in df.columns:
            return {
                "found": False,
                "submission_path": str(submission_path),
                "df": None,
                "enriched": None,
                "summary": None,
                "error": f"submission.csv missing required columns. Found: {list(df.columns)}",
            }
        summary = {
            "rows": len(df),
            "sales_sum": float(df["sales"].sum()),
            "sales_mean": float(df["sales"].mean()),
            "sales_min": float(df["sales"].min()),
            "sales_max": float(df["sales"].max()),
            "missing": int(df["sales"].isna().sum()),
            "negative": int((df["sales"] < 0).sum()),
        }
        enriched = None
        horizon_days = None
        date_min = None
        date_max = None
        date_min_fmt = None
        date_max_fmt = None
        if TEST_PATH.exists():
            try:
                test_df = pd.read_csv(TEST_PATH)
                if "id" in test_df.columns:
                    enriched = test_df.merge(df, on="id", how="left", suffixes=("", "_pred"))
                    if "sales_pred" in enriched.columns:
                        enriched["sales"] = enriched["sales_pred"]
                    if "date" in enriched.columns:
                        try:
                            enriched["date"] = pd.to_datetime(enriched["date"])
                            horizon_days = enriched["date"].nunique()
                            dmin = enriched["date"].min()
                            dmax = enriched["date"].max()
                            date_min = str(dmin.date())
                            date_max = str(dmax.date())
                            date_min_fmt = dmin.strftime("%d %B %Y")
                            date_max_fmt = dmax.strftime("%d %B %Y")
                            # also keep short range like "16 August – 31 August 2017"
                            date_min_short = dmin.strftime("%d %B")
                            date_max_short = dmax.strftime("%d %B %Y" if dmin.year != dmax.year else "%d %B %Y")
                            summary["date_range_short"] = f"{date_min_short} \u2013 {date_max_short}"
                        except Exception:
                            pass
                    summary["horizon_days"] = horizon_days
                    summary["date_min"] = date_min
                    summary["date_max"] = date_max
                    summary["date_min_fmt"] = date_min_fmt
                    summary["date_max_fmt"] = date_max_fmt
            except Exception as e:
                summary["enrich_error"] = str(e)
        return {
            "found": True,
            "submission_path": str(submission_path.relative_to(PROJECT_ROOT)) if submission_path.is_relative_to(PROJECT_ROOT) else str(submission_path),
            "df": df,
            "enriched": enriched,
            "summary": summary,
            "error": None,
        }
    except Exception as e:
        return {
            "found": False,
            "submission_path": str(submission_path),
            "df": None,
            "enriched": None,
            "summary": None,
            "error": str(e),
        }


def get_figures():
    if not FIGURES_DIR.exists():
        return []
    try:
        exts = {".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp"}
        files = [p for p in FIGURES_DIR.iterdir() if p.is_file() and p.suffix.lower() in exts]
        return sorted(files, key=lambda p: p.name)
    except Exception:
        return []


def get_error_analysis():
    top_families = [
        {"family": "GROCERY I", "abs_error": 669.87},
        {"family": "BEVERAGES", "abs_error": 563.82},
        {"family": "CLEANING", "abs_error": 341.39},
        {"family": "PRODUCE", "abs_error": 290.49},
        {"family": "DAIRY", "abs_error": 124.32},
    ]
    top_stores = [
        {"store_nbr": 44, "abs_error": 176.29},
        {"store_nbr": 47, "abs_error": 164.29},
        {"store_nbr": 48, "abs_error": 163.70},
        {"store_nbr": 45, "abs_error": 160.23},
        {"store_nbr": 46, "abs_error": 153.14},
    ]
    top_dates = [
        {"date": "2017-08-12", "abs_error": 127.44},
        {"date": "2017-08-01", "abs_error": 117.04},
        {"date": "2017-08-06", "abs_error": 100.78},
        {"date": "2017-08-13", "abs_error": 99.27},
        {"date": "2017-08-08", "abs_error": 93.58},
    ]
    return top_families, top_stores, top_dates


@app.route("/")
def index():
    forecast = load_forecast()
    figures = get_figures()
    top_families, top_stores, top_dates = get_error_analysis()

    # Derived display values (no new calculations beyond formatting)
    forecast_error_pct = f"{RIDGE_WAPE*100:.1f}%"
    simple_error_pct = f"{BASELINE_WAPE*100:.1f}%"
    improvement_pct = f"{IMPROVEMENT_PCT:.1f}%"

    # Expected sales total
    expected_sales_formatted = None
    expected_sales_short = None
    if forecast["found"] and forecast["summary"]:
        total = forecast["summary"]["sales_sum"]
        # Format as ₹13.02M
        expected_sales_formatted = f"\u20B9{total/1e6:.2f}M"
        expected_sales_short = f"{total:,.0f}"

    # Forecast period — actual test dates are 16 days (Aug 16-31 inclusive)
    # Use enriched summary if available, else fallback to hardcoded known range
    if forecast["found"] and forecast["summary"] and forecast["summary"].get("horizon_days"):
        horizon_days = forecast["summary"]["horizon_days"]
        date_range_short = forecast["summary"].get("date_range_short", "16 August \u2013 31 August 2017")
        date_min_fmt = forecast["summary"].get("date_min_fmt", "16 August 2017")
        date_max_fmt = forecast["summary"].get("date_max_fmt", "31 August 2017")
    else:
        horizon_days = 16
        date_range_short = "16 August \u2013 31 August 2017"
        date_min_fmt = "16 August 2017"
        date_max_fmt = "31 August 2017"

    # Prepare forecast table with friendly column names
    forecast_table = None
    forecast_columns = []
    friendly_columns = []
    table_total_rows = 0
    if forecast["found"] and forecast["df"] is not None:
        if forecast["enriched"] is not None:
            desired = ["date", "store_nbr", "family", "onpromotion", "sales"]
            available = [c for c in desired if c in forecast["enriched"].columns]
            forecast_table = forecast["enriched"][available].head(50)
            table_total_rows = len(forecast["enriched"])
            # Map to friendly names for display
            col_map = {
                "date": "Date",
                "store_nbr": "Store",
                "family": "Product category",
                "onpromotion": "Promotion items",
                "sales": "Expected sales",
            }
            friendly_columns = [col_map.get(c, c) for c in available]
            forecast_columns = available
        else:
            forecast_table = forecast["df"].head(50)
            table_total_rows = len(forecast["df"])
            forecast_columns = list(forecast["df"].columns)
            friendly_columns = ["ID" if c=="id" else "Expected sales" if c=="sales" else c for c in forecast_columns]

        if forecast_table is not None and "date" in forecast_table.columns:
            forecast_table = forecast_table.copy()
            forecast_table["date"] = pd.to_datetime(forecast_table["date"]).dt.strftime("%Y-%m-%d")
        # Format sales for display but keep numeric for template logic
        table_records = forecast_table.to_dict(orient="records") if forecast_table is not None else []
    else:
        table_records = []
        friendly_columns = []

    dataset_info = {}
    if TRAIN_PATH.exists():
        try:
            train_head = pd.read_csv(TRAIN_PATH, nrows=3)
            dataset_info["train_cols"] = list(train_head.columns)
        except Exception:
            dataset_info["train_cols"] = ["id", "date", "store_nbr", "family", "sales", "onpromotion"]
    else:
        dataset_info["train_cols"] = ["id", "date", "store_nbr", "family", "sales", "onpromotion"]

    figure_names = [f.name for f in figures]

    return render_template(
        "index.html",
        ridge_wape=RIDGE_WAPE,
        baseline_wape=BASELINE_WAPE,
        naive_wape=NAIVE_WAPE,
        improvement=IMPROVEMENT_PCT,
        forecast_error_pct=forecast_error_pct,
        simple_error_pct=simple_error_pct,
        improvement_pct=improvement_pct,
        expected_sales_formatted=expected_sales_formatted,
        expected_sales_short=expected_sales_short,
        horizon_days=horizon_days,
        date_range_short=date_range_short,
        date_min_fmt=date_min_fmt,
        date_max_fmt=date_max_fmt,
        forecast=forecast,
        figures=figure_names,
        figures_dir_exists=FIGURES_DIR.exists(),
        forecast_table=table_records,
        forecast_columns=forecast_columns,
        friendly_columns=friendly_columns,
        table_total_rows=table_total_rows,
        top_families=top_families,
        top_stores=top_stores,
        top_dates=top_dates,
        dataset_info=dataset_info,
    )


@app.route("/reports/figures/<path:filename>")
def serve_figure(filename):
    if not FIGURES_DIR.exists():
        abort(404)
    allowed = {".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp"}
    if Path(filename).suffix.lower() not in allowed:
        abort(404)
    return send_from_directory(str(FIGURES_DIR), filename)


@app.route("/health")
def health():
    return {"status": "ok", "ridge_wape": RIDGE_WAPE, "baseline_wape": BASELINE_WAPE}


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=False)
